/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import entidades.Materia;
import javax.swing.JOptionPane;
import persistencia.MateriaData;

/**
 *
 * @author Humberto
 */
public class gestionDeMaterias extends javax.swing.JFrame {

    private Menu_principal menu =new Menu_principal();
    
    private MateriaData materiaData = new MateriaData(menu.conexionDb());
    
    public gestionDeMaterias() {
        initComponents();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JB_guardar = new javax.swing.JButton();
        JB_eliminar = new javax.swing.JButton();
        JB_modificar = new javax.swing.JButton();
        JB_salir = new javax.swing.JButton();
        JB_buscar = new javax.swing.JButton();
        JTF_idmateria = new javax.swing.JTextField();
        JTF_nombre = new javax.swing.JTextField();
        JTF_semestre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JRB_estado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("MATERIA");

        jLabel2.setText("ID Materia :");

        jLabel3.setText("Nombre :");

        jLabel4.setText("Semestre :");

        JB_guardar.setText("Guardar");
        JB_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_guardarActionPerformed(evt);
            }
        });

        JB_eliminar.setText("Eliminar");
        JB_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_eliminarActionPerformed(evt);
            }
        });

        JB_modificar.setText("Modificar");
        JB_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_modificarActionPerformed(evt);
            }
        });

        JB_salir.setText("Salir");
        JB_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_salirActionPerformed(evt);
            }
        });

        JB_buscar.setText("Buscar");
        JB_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_buscarActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado :");

        JRB_estado.setText("Activar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_guardar)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTF_idmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JB_eliminar)
                                .addGap(18, 18, 18)
                                .addComponent(JB_modificar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_buscar)
                            .addComponent(JB_salir)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JRB_estado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTF_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(JTF_semestre, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTF_idmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JB_buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRB_estado))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_guardar)
                    .addComponent(JB_eliminar)
                    .addComponent(JB_modificar)
                    .addComponent(JB_salir))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_salirActionPerformed
          // BOTON DE SALIR
        dispose();
    }//GEN-LAST:event_JB_salirActionPerformed

    private void JB_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_guardarActionPerformed
        //Guardar 
        if (!JTF_idmateria.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El codigo tiene que estar vacio");
        } else if (JTF_nombre.getText().equals("") || JTF_semestre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No puede tener campos vacios");
        } else {
            try {
                Materia materia = new Materia();

                materia.setNombre(JTF_nombre.getText());
                materia.setAnio(Integer.parseInt(JTF_semestre.getText()));
                materia.setEstado(JRB_estado.isSelected());

                materiaData.guardarMateria(materia);
                limpiar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese un Año en formato de numero");
            }
        }
    }//GEN-LAST:event_JB_guardarActionPerformed

    private void JB_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_buscarActionPerformed
        // Buscar
        
         try {
            int id = Integer.parseInt(JTF_idmateria.getText());

            Materia materia = materiaData.buscarMateriaPorId(id);

            if (materia != null) {
                JTF_nombre.setText(materia.getNombre());
                JTF_semestre.setText(String.valueOf(materia.getAnio()));
                JRB_estado.setSelected(materia.isEstado());
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Debe agregar un id válido");
            JTF_idmateria.requestFocusInWindow();
        }
    }//GEN-LAST:event_JB_buscarActionPerformed

    private void JB_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_modificarActionPerformed
        // Actualizar
        Materia mat = new Materia();

        if (!isNumeric(JTF_idmateria.getText())) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el ID de la materia.");
            JTF_idmateria.requestFocusInWindow();
        } else if (!isNumeric(JTF_semestre.getText())) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un año válido.");
            JTF_semestre.requestFocusInWindow();
        } else if (JTF_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre");
            JTF_nombre.requestFocusInWindow();
        } else {
            mat.setIdMateria(Integer.parseInt(JTF_idmateria.getText()));
            mat.setNombre(JTF_nombre.getText());
            mat.setAnio(Integer.parseInt(JTF_semestre.getText()));
            mat.setEstado(JRB_estado.isSelected());
            materiaData.modificarMateria(mat);
            limpiar();
        }
    }//GEN-LAST:event_JB_modificarActionPerformed

    private void JB_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_eliminarActionPerformed
        // Eliminar
         if (!isNumeric(JTF_idmateria.getText())) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el ID de la materia.");
            JTF_idmateria.requestFocusInWindow();
        } else {
            int codigo = Integer.parseInt(JTF_idmateria.getText());
            Materia materia = materiaData.buscarMateriaPorId(codigo);
            if (materia != null) {
                materiaData.eliminarMateria(materia.getIdMateria());
                JOptionPane.showMessageDialog(null, "Materia eliminada correctamente");
            }
            limpiar();
        }
    }//GEN-LAST:event_JB_eliminarActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(gestionDeMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(gestionDeMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(gestionDeMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(gestionDeMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new gestionDeMaterias().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_buscar;
    private javax.swing.JButton JB_eliminar;
    private javax.swing.JButton JB_guardar;
    private javax.swing.JButton JB_modificar;
    private javax.swing.JButton JB_salir;
    private javax.swing.JRadioButton JRB_estado;
    private javax.swing.JTextField JTF_idmateria;
    private javax.swing.JTextField JTF_nombre;
    private javax.swing.JTextField JTF_semestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

   private void limpiar() {
        // borra los datos de los textField
        JRB_estado.setSelected(false);
        JTF_semestre.setText("");
        JTF_idmateria.setText("");
        JTF_nombre.setText("");
    }
    private static boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }


}
