/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import entidades.*;
import java.util.List;
import javax.swing.JOptionPane;
import persistencia.*;



public class ingresarNota extends javax.swing.JFrame {
    
    Menu_principal menu =new Menu_principal();
    AlumnoData alumnoData = new AlumnoData(menu.conexionDb());
    InscripcionData inscripcionData = new InscripcionData(menu.conexionDb());
   
    public ingresarNota() {
        initComponents();
        setLocationRelativeTo(null);
        configurarEventoCambioAnio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF_id = new javax.swing.JTextField();
        JB_buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TF_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JCB_materia = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        JCB_anio = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TF_nota = new javax.swing.JTextField();
        JB_guardar = new javax.swing.JButton();
        JB_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ALUMNO");

        jLabel2.setText("ID Alumnos :");

        JB_buscar.setText("Buscar");
        JB_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre :");

        jLabel4.setText("Apellido :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("MATERIA INSCRIPTA");

        jLabel6.setText("Materia :");

        jLabel7.setText("Año de inscripcion :");

        JCB_anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2024", "2023", "2022" }));

        jLabel8.setText("Nota :");

        TF_nota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        JB_guardar.setText("Guardar");
        JB_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_guardarActionPerformed(evt);
            }
        });

        JB_volver.setText("Salir");
        JB_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCB_anio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_id)
                            .addComponent(TF_nombre)
                            .addComponent(TF_apellido)
                            .addComponent(JCB_materia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_nota)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JB_guardar)
                                .addGap(94, 94, 94)
                                .addComponent(JB_volver)
                                .addGap(0, 3, Short.MAX_VALUE)))))
                .addGap(30, 30, 30)
                .addComponent(JB_buscar)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JCB_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JCB_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TF_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_guardar)
                    .addComponent(JB_volver))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_volverActionPerformed
        dispose();
    }//GEN-LAST:event_JB_volverActionPerformed

    private void JB_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_buscarActionPerformed
        try {
            int id = Integer.parseInt(TF_id.getText());

            Alumno alum = alumnoData.buscarAlumnoPorId(id);

            if (alum != null && alum.isEstado()) {
               TF_apellido.setText(alum.getApellido());
               TF_nombre.setText(alum.getNombre());
            
           
               cargarComboMaterias(alum.getIdAlumno());
            } else {
               JOptionPane.showMessageDialog(this, "Alumno no encontrado","INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
               JCB_materia.removeAllItems();
        }
        } catch (NumberFormatException ex) {
              JOptionPane.showMessageDialog(null, "Debe ingresar un ID válido","ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JB_buscarActionPerformed

    private void JB_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_guardarActionPerformed
        try {
        Alumno alum = alumnoData.buscarAlumnoPorId(Integer.parseInt(TF_id.getText()));
        if (alum == null || !alum.isEstado()) {
            JOptionPane.showMessageDialog(this, "Alumno inválido","INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Materia seleccion = (Materia) JCB_materia.getSelectedItem();
        if (seleccion == null || seleccion.getIdMateria() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una materia válida","INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        double nota = Double.parseDouble(TF_nota.getText());
        int idAlumno = alum.getIdAlumno();
        int idMateria = seleccion.getIdMateria();
        int anio = Integer.parseInt(JCB_anio.getSelectedItem().toString());

        inscripcionData.actualizarNota(idAlumno, idMateria, anio, nota);

        JOptionPane.showMessageDialog(this, "Nota guardada correctamente","INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
       } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese una nota válida","ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_JB_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ingresarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ingresarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ingresarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ingresarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ingresarNota().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_buscar;
    private javax.swing.JButton JB_guardar;
    private javax.swing.JButton JB_volver;
    private javax.swing.JComboBox<String> JCB_anio;
    private javax.swing.JComboBox<Materia> JCB_materia;
    private javax.swing.JTextField TF_apellido;
    private javax.swing.JTextField TF_id;
    private javax.swing.JTextField TF_nombre;
    private javax.swing.JTextField TF_nota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
    private void cargarComboMaterias(int idAlumno) {
     JCB_materia.removeAllItems();

        if (JCB_anio.getSelectedItem() == null || JCB_anio.getSelectedItem().toString().trim().isEmpty()) {
            return;
           }

        int anio = Integer.parseInt(JCB_anio.getSelectedItem().toString());
        List<Materia> materiasInscriptas = inscripcionData.obtenerMateriasCursadas(idAlumno, anio);

        if (materiasInscriptas == null || materiasInscriptas.isEmpty()) {
            JCB_materia.addItem(new Materia(-1, "Sin materias inscriptas", 0, false));
            return;
           }

        for (Materia m : materiasInscriptas) {
            JCB_materia.addItem(m); 
           }
   }
    
   private void configurarEventoCambioAnio() {
    JCB_anio.addActionListener(e -> {
        if (!TF_id.getText().isEmpty()) {
            try {
                int id = Integer.parseInt(TF_id.getText());
                Alumno alum = alumnoData.buscarAlumnoPorId(id);
                if (alum != null && alum.isEstado()) {
                    cargarComboMaterias(alum.getIdAlumno());
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "ID de alumno inválido","ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                JCB_materia.removeAllItems();
            }
        }
    });
} 


}
