/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import persistencia.Conexion;

/**
 *
 * @author Humberto
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_alumno = new javax.swing.JMenu();
        JM_formularioAlumno = new javax.swing.JMenuItem();
        JM_materia = new javax.swing.JMenu();
        JM_formularioMateria = new javax.swing.JMenuItem();
        JM_inscripcion = new javax.swing.JMenu();
        JM_manejoInscripcion = new javax.swing.JMenuItem();
        JM_ingresarNotas = new javax.swing.JMenuItem();
        JM_consulta = new javax.swing.JMenu();
        JM_listarAlumnos = new javax.swing.JMenuItem();
        JM_listarMateria = new javax.swing.JMenuItem();
        JM_listarAlumnosXMateria = new javax.swing.JMenuItem();
        JM_listarMateriaXAlumnos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        JM_alumno.setText("Alumno");
        JM_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_alumnoActionPerformed(evt);
            }
        });

        JM_formularioAlumno.setText("Formulario Alumno");
        JM_formularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_formularioAlumnoActionPerformed(evt);
            }
        });
        JM_alumno.add(JM_formularioAlumno);

        jMenuBar1.add(JM_alumno);

        JM_materia.setText("Materia");

        JM_formularioMateria.setText("Formulario Materia");
        JM_formularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_formularioMateriaActionPerformed(evt);
            }
        });
        JM_materia.add(JM_formularioMateria);

        jMenuBar1.add(JM_materia);

        JM_inscripcion.setText("Inscripciones");

        JM_manejoInscripcion.setText("Manejo de inscripciones ");
        JM_manejoInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_manejoInscripcionActionPerformed(evt);
            }
        });
        JM_inscripcion.add(JM_manejoInscripcion);

        JM_ingresarNotas.setText("Ingresar notas");
        JM_ingresarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_ingresarNotasActionPerformed(evt);
            }
        });
        JM_inscripcion.add(JM_ingresarNotas);

        jMenuBar1.add(JM_inscripcion);

        JM_consulta.setText("Consultas");

        JM_listarAlumnos.setText("Listar Alumno");
        JM_listarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_listarAlumnosActionPerformed(evt);
            }
        });
        JM_consulta.add(JM_listarAlumnos);

        JM_listarMateria.setText("Listar Materia");
        JM_listarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_listarMateriaActionPerformed(evt);
            }
        });
        JM_consulta.add(JM_listarMateria);

        JM_listarAlumnosXMateria.setText("Listar alumnos por materia");
        JM_listarAlumnosXMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_listarAlumnosXMateriaActionPerformed(evt);
            }
        });
        JM_consulta.add(JM_listarAlumnosXMateria);

        JM_listarMateriaXAlumnos.setText("Listar materias por alumno");
        JM_listarMateriaXAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_listarMateriaXAlumnosActionPerformed(evt);
            }
        });
        JM_consulta.add(JM_listarMateriaXAlumnos);

        jMenuBar1.add(JM_consulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JM_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JM_alumnoActionPerformed

    private void JM_formularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_formularioAlumnoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
        gestionDeAlumnos GUI = new gestionDeAlumnos();
        GUI.setVisible(true);
        
        escritorio.add(GUI);
        escritorio.moveToFront(GUI);
    }//GEN-LAST:event_JM_formularioAlumnoActionPerformed

    private void JM_formularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_formularioMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        gestionDeMaterias GUI = new gestionDeMaterias();
        GUI.setVisible(true);
        
        escritorio.add(GUI);
        escritorio.moveToFront(GUI);
    }//GEN-LAST:event_JM_formularioMateriaActionPerformed

    private void JM_listarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_listarAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
        listarAlumnos GUI = new listarAlumnos();
        GUI.setVisible(true);
        
        escritorio.add(GUI);
        escritorio.moveToFront(GUI);
    }//GEN-LAST:event_JM_listarAlumnosActionPerformed

    private void JM_listarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_listarMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
        listarMaterias GUI = new listarMaterias();
        GUI.setVisible(true);
        
        escritorio.add(GUI);
        escritorio.moveToFront(GUI);
    }//GEN-LAST:event_JM_listarMateriaActionPerformed

    private void JM_listarAlumnosXMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_listarAlumnosXMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        alumnosPorMaterias GUI = new alumnosPorMaterias();
        GUI.setVisible(true);
        
        escritorio.add(GUI);
        escritorio.moveToFront(GUI);
    }//GEN-LAST:event_JM_listarAlumnosXMateriaActionPerformed

    private void JM_listarMateriaXAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_listarMateriaXAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        materiaPorAlumno GUI = new materiaPorAlumno();
        GUI.setVisible(true);
        
        escritorio.add(GUI);
        escritorio.moveToFront(GUI);
    }//GEN-LAST:event_JM_listarMateriaXAlumnosActionPerformed

    private void JM_manejoInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_manejoInscripcionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        inscripciones GUI = new inscripciones();
        GUI.setVisible(true);
        
        escritorio.add(GUI);
        escritorio.moveToFront(GUI);
    }//GEN-LAST:event_JM_manejoInscripcionActionPerformed

    private void JM_ingresarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_ingresarNotasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        ingresarNota GUI = new ingresarNota();
        GUI.setVisible(true);
        
        escritorio.add(GUI);
        escritorio.moveToFront(GUI);
    }//GEN-LAST:event_JM_ingresarNotasActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu_principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JM_alumno;
    private javax.swing.JMenu JM_consulta;
    private javax.swing.JMenuItem JM_formularioAlumno;
    private javax.swing.JMenuItem JM_formularioMateria;
    private javax.swing.JMenuItem JM_ingresarNotas;
    private javax.swing.JMenu JM_inscripcion;
    private javax.swing.JMenuItem JM_listarAlumnos;
    private javax.swing.JMenuItem JM_listarAlumnosXMateria;
    private javax.swing.JMenuItem JM_listarMateria;
    private javax.swing.JMenuItem JM_listarMateriaXAlumnos;
    private javax.swing.JMenuItem JM_manejoInscripcion;
    private javax.swing.JMenu JM_materia;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

public Conexion conexionDb(){
    Conexion conn = new Conexion("grupo_9_universidad","jdbc:mariadb://localhost/","root","","org.mariadb.jdbc.Driver");
    return conn;
}


}
